In [2]:
import numpy as np;

a = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
np.size(a)

In [ ]:
np.shape(a)

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
np.shape(a)

(10,)

In [ ]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

In [ ]:
np.array(np_mix_matrix[:,1], dtype = int)

In [8]:
np.random.seed(1)
np.round(np.random.rand(5,5)*1000)

array([[417., 720.,   0., 302., 147.],
       [ 92., 186., 346., 397., 539.],
       [419., 685., 204., 878.,  27.],
       [670., 417., 559., 140., 198.],
       [801., 968., 313., 692., 876.]])

In [9]:

a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([ 2,  9,  9,  4, 10])

In [10]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False)

array([10,  3,  1,  5,  2])

In [116]:
np_mix_matrix = np.array([['3',2],['three',4],['five',6]])
np_mix_matrix

array([['3', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [58]:
np_matrix = np.random.rand(5,5)
idx_choose = np.random.choice(5,3)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [18]:

#ex2

np_matrix = np.random.rand(10,5)
idx_choose = np.round(np_matrix[:,-1])
np_matrix[:,-1] = idx_choose
np_matrix


array([[0.35956031, 0.55403215, 0.41135441, 0.96604656, 0.        ],
       [0.99282657, 0.65919996, 0.80907724, 0.45815087, 1.        ],
       [0.53393433, 0.57727945, 0.91749829, 0.31414652, 1.        ],
       [0.80523584, 0.48006293, 0.48757437, 0.84141006, 1.        ],
       [0.26988129, 0.48674271, 0.27584589, 0.22539047, 1.        ],
       [0.92113358, 0.20047475, 0.8798531 , 0.4658077 , 1.        ],
       [0.30287132, 0.48900729, 0.20367433, 0.08861626, 0.        ],
       [0.50299653, 0.78758101, 0.90360187, 0.21952409, 1.        ],
       [0.25780289, 0.56420874, 0.13242963, 0.37208768, 0.        ],
       [0.50572622, 0.69440685, 0.45697791, 0.36127471, 1.        ]])

In [ ]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

In [ ]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

In [ ]:
i,j = np.where(np_matrix == 2)

In [ ]:
i

In [ ]:
j

In [ ]:
##idx = [1,2,3,4,5]
##np_matrix[idx,:]
#because index start at 0 and end by n-1

idx = [0,1,2,3,4]
np_matrix[idx,:]

In [130]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix
i,j = np.where(np_matrix == 2)
i

array([0, 1, 2, 4, 4])

In [151]:
#ex4

np_matrix = np.random.randint(10,size=(10,5))
vector = np.random.randint(2,size=10)
np_matrix

#train_data

#np_random = np.random.choice(np_matrix,10)
#np_random

array([[7, 9, 9, 6, 1],
       [9, 7, 8, 3, 2],
       [9, 1, 0, 2, 9],
       [3, 7, 0, 4, 4],
       [5, 0, 9, 7, 8],
       [4, 9, 9, 4, 2],
       [9, 0, 4, 5, 6],
       [9, 9, 2, 0, 6],
       [3, 1, 1, 1, 2],
       [6, 9, 2, 0, 5]])

In [154]:
#ex4
vector

array([0, 1, 0, 0, 1, 1, 1, 0, 0, 1])

In [155]:
#ex4
train_data = np_matrix[(vector==0)]
train_data


array([[7, 9, 9, 6, 1],
       [9, 1, 0, 2, 9],
       [3, 7, 0, 4, 4],
       [9, 9, 2, 0, 6],
       [3, 1, 1, 1, 2]])

In [158]:
#ex4
test_data = np_matrix[(vector==1)]
test_data

array([[9, 7, 8, 3, 2],
       [5, 0, 9, 7, 8],
       [4, 9, 9, 4, 2],
       [9, 0, 4, 5, 6],
       [6, 9, 2, 0, 5]])

In [73]:
data = np.random.randint(5,size=(5,5)) + 1
data

array([[5, 1, 4, 1, 5],
       [5, 5, 3, 5, 4],
       [1, 1, 2, 3, 5],
       [1, 5, 5, 1, 3],
       [1, 5, 2, 1, 2]])

In [75]:
np.max(data,1)

array([5, 5, 5, 5, 5])

In [115]:
#ex 5 
np.sort(data[0,:])[::-1]

array([5, 5, 4, 1, 1])

In [177]:
np_test= np.arange(25).reshape(5,5)
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [178]:
#ex 6

np_test[(np_test%3==0)]


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [183]:
#ex7
np_test[np.eye(5)==1] = 0
np_test