In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [11]:
df = pd.read_csv('https://raw.githubusercontent.com/plenoi/CMU_DataSCience/master/lung.csv', header=None)
df

0         1         2         3         4         5         6     \
0       1 -0.953518 -0.433265 -0.926334 -0.878343 -0.940477 -0.881761   
1       1 -0.976293 -0.750423 -0.941069 -0.980535 -0.994048 -0.925679   
2       1 -0.663669 -0.491751 -0.893186 -0.854013 -0.934524 -0.842909   
3       1 -0.852158 -0.730928 -0.697973 -0.970803 -0.928571 -0.940880   
4       1 -0.987727 -0.858310 -0.985267 -0.975669 -1.000000 -0.988176   
..    ...       ...       ...       ...       ...       ...       ...   
627     0 -0.938026 -0.324072 -0.871086 -0.367380 -0.755951 -0.505091   
628     0 -0.930654 -0.361768 -0.933701 -0.902674 -0.976190 -0.937502   
629     0 -0.905128 -0.149886 -0.882138 -0.751823 -0.940477 -0.896964   
630     0 -0.985533 -0.799825 -0.996317 -0.970803 -0.994048 -0.998311   
631     0 -0.985393 -0.815414 -0.985267 -0.995134 -1.000000 -0.994933   

         7         8         9     ...      1271      1272      1273  \
0   -0.555303 -0.866727 -0.339190  ...  0.111509 -0.842061 -0.984096   
1   -0.844926 -0.942945 -0.778852  ...  0.256599 -0.918326 -0.997074   
2   -0.792472 -0.907733 -0.490566  ...  0.184607 -0.844687 -0.969846   
3   -0.621438 -0.958102 -0.739355  ...  0.496361 -0.900450 -0.989313   
4   -0.908780 -0.938043 -0.861778  ...  0.565058 -0.545379 -0.996183   
..        ...       ...       ...  ...       ...       ...       ...   
627 -0.582674 -0.966124 -0.377365  ... -0.237275 -0.893069 -0.995038   
628 -0.603191 -0.728547 -0.291794  ...  0.555847 -0.403511 -0.934094   
629 -0.290764 -0.691552 -0.118042  ...  0.469137 -0.357597 -0.914628   
630 -0.872292 -0.915757 -0.809127  ...  0.732931 -0.573425 -0.970355   
631 -0.879133 -0.926900 -0.815704  ...  0.714058 -0.585071 -0.978370   

         1274      1275      1276      1277      1278      1279      1280  
0   -0.641238 -0.611943 -0.852940 -0.891501 -0.737089 -0.879686 -0.998865  
1   -0.912676 -0.895525 -0.985294 -0.945752 -0.768386 -0.942223 -0.999525  
2   -0.038363 -0.425380 -0.887256 -0.938516 -0.729780 -0.903817 -0.979734  
3   -0.681212 -0.701494 -0.936275 -0.978300 -0.814291 -0.920470 -0.992083  
4   -0.910572 -0.880595 -0.990196 -1.000000 -0.854985 -0.555620 -0.988864  
..        ...       ...       ...       ...       ...       ...       ...  
627 -0.930562 -0.873133 -0.877452 -0.938516 -0.806991 -0.857425 -0.998654  
628 -0.545495 -0.679108 -0.877452 -0.927667 -0.845587 -0.432757 -0.974535  
629 -0.360328 -0.485076 -0.818625 -0.905969 -0.832032 -0.350340 -0.970445  
630 -0.815885 -0.865671 -0.921566 -0.992767 -0.880016 -0.598787 -0.972266  
631 -0.862177 -0.746272 -0.916665 -0.992767 -0.883149 -0.633289 -0.968412  

[632 rows x 1281 columns]

In [12]:
df.isnull().sum(axis=0)

0       0
1       0
2       0
3       0
4       0
       ..
1276    0
1277    0
1278    0
1279    0
1280    0
Length: 1281, dtype: int64

In [13]:
df.isnull().sum(axis=1)

0      0
1      0
2      0
3      0
4      0
      ..
627    0
628    0
629    0
630    0
631    0
Length: 632, dtype: int64

In [14]:
df_clean = df.dropna()

In [15]:
df_clean.isnull().sum(axis=1)

0      0
1      0
2      0
3      0
4      0
      ..
627    0
628    0
629    0
630    0
631    0
Length: 632, dtype: int64

In [16]:
df_clean.isnull().sum(axis=0)

0       0
1       0
2       0
3       0
4       0
       ..
1276    0
1277    0
1278    0
1279    0
1280    0
Length: 1281, dtype: int64

In [17]:
df_clean.shape

(632, 1281)

In [18]:
cancerClass = np.unique(df_clean[0])
cancerClass

array([0, 1])

In [19]:
cancerStatus = [sum(df_clean[0]==cancerClass[0]),
                sum(df_clean[0]==cancerClass[1])]
cancerStatus

[304, 328]

In [20]:
y=df_clean[0].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [21]:
X=df_clean.drop(0,axis=1).values
X

array([[-0.953518, -0.433265, -0.926334, ..., -0.737089, -0.879686,
        -0.998865],
       [-0.976293, -0.750423, -0.941069, ..., -0.768386, -0.942223,
        -0.999525],
       [-0.663669, -0.491751, -0.893186, ..., -0.72978 , -0.903817,
        -0.979734],
       ...,
       [-0.905128, -0.149886, -0.882138, ..., -0.832032, -0.35034 ,
        -0.970445],
       [-0.985533, -0.799825, -0.996317, ..., -0.880016, -0.598787,
        -0.972266],
       [-0.985393, -0.815414, -0.985267, ..., -0.883149, -0.633289,
        -0.968412]])

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [23]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [24]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
fs = SelectKBest(chi2, k=600)
fs.fit(X_train, y_train)
X_test_norm = fs.transform(X_test)
X_train_norm = fs.transform(X_train)
X_train.shape


(442, 1280)

In [26]:
X_train_norm.shape

(442, 600)

In [27]:
X_test_norm.shape

(190, 600)

In [ ]:
from sklearn.ensemble import StackingClassifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from catboost import CatBoostClassifier

from sklearn.naive_bayes import GaussianNB


clf1 = CatBoostClassifier(random_state=1,verbose=False,iterations=50,learning_rate=1)

clf2 = CatBoostClassifier(random_state=1,verbose=False,iterations=50,learning_rate=1)

clf3 = CatBoostClassifier(random_state=1,verbose=False,iterations=50,learning_rate=1)

clf4 = CatBoostClassifier(random_state=1,verbose=False,iterations=50,learning_rate=1)

clf5 = GaussianNB()

eclf = StackingClassifier(

estimators=[('cb1', clf1), ('cb2', clf2), ('cb3', clf3) , ('cb4',clf4) , ('gnb',clf5)],

stack_method = 'predict_proba',

final_estimator= CatBoostClassifier(random_state=1,iterations=51))

params = {'cb1__depth': [1,5], 'cb2__depth': [1,5] , 'cb3__depth':[1,5] ,'cb4__depth':[1,5] ,}

grid = GridSearchCV(estimator=eclf, param_grid=params, cv=5)

grid = grid.fit(X_train_norm,y_train)

print("Best params : " + str(grid.best_params_))
print("10CV accuracy : "+str(grid.best_score_*100))

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
y_predict = grid.predict(X_test_norm)

target_names = ['negative', 'positive']
sum(y_test == y_predict)/len(y_test)

In [3]:

df_test = pd.read_csv('https://raw.githubusercontent.com/plenoi/CMU_DataScience/master/lung_test.csv?fbclid=IwAR0If2OR6u5Zr4qazH4N4lp4ZCz864asgMAhevSYBS-mlH7zixoJfgT2R4E', header=None)
df_test


0         1         2         3         4         5         6     \
0       1 -0.979046 -0.716633 -0.981584 -0.961070 -0.964285 -0.962839   
1       1 -0.887534 -0.057599 -0.963168 -0.941605 -0.958333 -0.915544   
2       1 -0.976713 -0.802425 -0.970534 -0.985401 -0.988095 -0.961150   
3       1 -0.961500 -0.645135 -0.944753 -0.902674 -0.970238 -0.917232   
4       1 -0.958373 -0.249974 -0.845303 -0.892944 -0.904763 -0.903720   
..    ...       ...       ...       ...       ...       ...       ...   
267     0 -0.945586  0.230922 -0.454894 -0.489033 -0.607139 -0.505091   
268     0 -0.942505 -0.586638 -0.790055 -0.742090 -0.648807 -0.826015   
269     0 -0.988380 -0.857016 -0.922653 -0.863746 -0.875001 -0.932435   
270     0 -0.972186 -0.915509 -0.896870 -0.888077 -0.821427 -0.934124   
271     0 -0.950626 -0.613945 -0.841619 -0.746957 -0.648807 -0.881761   

         7         8         9     ...      1271      1272      1273  \
0   -0.849486 -0.900600 -0.732778  ... -0.007953 -0.835510 -0.991348   
1   -0.473192 -0.694227 -0.081178  ...  0.137629 -0.508157 -0.921880   
2   -0.831243 -0.907733 -0.740678  ...  0.281941 -0.770071 -0.989058   
3   -0.753708 -0.845328 -0.591923  ...  0.445740 -0.560465 -0.972264   
4   -0.377416 -0.864943 -0.286527  ...  0.357187 -0.798273 -0.983715   
..        ...       ...       ...  ...       ...       ...       ...   
267 -0.069551 -0.778469  0.136026  ... -0.422793 -0.180304 -0.929768   
268 -0.231462 -0.941610 -0.523474  ...  0.106617 -0.823535 -0.990712   
269 -0.559865 -0.957211 -0.820971  ...  0.453743 -0.800414 -0.995038   
270 -0.765102 -0.987074 -0.905221  ...  0.660038 -0.796146 -0.995165   
271 -0.359169 -0.946959 -0.519530  ...  0.038064 -0.853379 -0.989949   

         1274      1275      1276      1277      1278      1279      1280  
0   -0.860071 -0.925373 -1.000000 -1.000000 -0.581632 -0.841275 -0.997440  
1   -0.315089  0.074620 -0.897059 -0.949368 -0.727701 -0.545253 -0.966538  
2   -0.701209 -0.932835 -1.000000 -0.996383 -0.749610 -0.756818 -0.993245  
3   -0.674904 -0.305949 -0.872551 -0.949368 -0.640058 -0.580938 -0.991529  
4   -0.585479 -0.365677 -0.833334 -0.887884 -0.826811 -0.819876 -0.996596  
..        ...       ...       ...       ...       ...       ...       ...  
267 -0.335076  1.089560 -0.049037 -0.385160 -0.342718 -0.081677 -0.855971  
268 -0.900055 -0.813437 -0.936275 -0.898733 -0.586853 -0.836350 -0.998654  
269 -0.936874 -0.738810 -0.926472 -0.945752 -0.744389 -0.826324 -0.998681  
270 -0.956864 -0.888063 -0.975490 -0.938516 -0.907145 -0.793863 -0.996860  
271 -0.860071 -0.716418 -0.887256 -0.905969 -0.745433 -0.871529 -0.998918  

[272 rows x 1281 columns]

In [4]:
df_test.isnull().any


df_test.isnull().sum(axis=1)

0      0
1      0
2      0
3      0
4      0
      ..
267    0
268    0
269    0
270    0
271    0
Length: 272, dtype: int64

In [5]:
df_test.isnull().sum(axis=0)

0       0
1       0
2       0
3       0
4       0
       ..
1276    0
1277    0
1278    0
1279    0
1280    0
Length: 1281, dtype: int64

In [6]:
df_test

0         1         2         3         4         5         6     \
0       1 -0.979046 -0.716633 -0.981584 -0.961070 -0.964285 -0.962839   
1       1 -0.887534 -0.057599 -0.963168 -0.941605 -0.958333 -0.915544   
2       1 -0.976713 -0.802425 -0.970534 -0.985401 -0.988095 -0.961150   
3       1 -0.961500 -0.645135 -0.944753 -0.902674 -0.970238 -0.917232   
4       1 -0.958373 -0.249974 -0.845303 -0.892944 -0.904763 -0.903720   
..    ...       ...       ...       ...       ...       ...       ...   
267     0 -0.945586  0.230922 -0.454894 -0.489033 -0.607139 -0.505091   
268     0 -0.942505 -0.586638 -0.790055 -0.742090 -0.648807 -0.826015   
269     0 -0.988380 -0.857016 -0.922653 -0.863746 -0.875001 -0.932435   
270     0 -0.972186 -0.915509 -0.896870 -0.888077 -0.821427 -0.934124   
271     0 -0.950626 -0.613945 -0.841619 -0.746957 -0.648807 -0.881761   

         7         8         9     ...      1271      1272      1273  \
0   -0.849486 -0.900600 -0.732778  ... -0.007953 -0.835510 -0.991348   
1   -0.473192 -0.694227 -0.081178  ...  0.137629 -0.508157 -0.921880   
2   -0.831243 -0.907733 -0.740678  ...  0.281941 -0.770071 -0.989058   
3   -0.753708 -0.845328 -0.591923  ...  0.445740 -0.560465 -0.972264   
4   -0.377416 -0.864943 -0.286527  ...  0.357187 -0.798273 -0.983715   
..        ...       ...       ...  ...       ...       ...       ...   
267 -0.069551 -0.778469  0.136026  ... -0.422793 -0.180304 -0.929768   
268 -0.231462 -0.941610 -0.523474  ...  0.106617 -0.823535 -0.990712   
269 -0.559865 -0.957211 -0.820971  ...  0.453743 -0.800414 -0.995038   
270 -0.765102 -0.987074 -0.905221  ...  0.660038 -0.796146 -0.995165   
271 -0.359169 -0.946959 -0.519530  ...  0.038064 -0.853379 -0.989949   

         1274      1275      1276      1277      1278      1279      1280  
0   -0.860071 -0.925373 -1.000000 -1.000000 -0.581632 -0.841275 -0.997440  
1   -0.315089  0.074620 -0.897059 -0.949368 -0.727701 -0.545253 -0.966538  
2   -0.701209 -0.932835 -1.000000 -0.996383 -0.749610 -0.756818 -0.993245  
3   -0.674904 -0.305949 -0.872551 -0.949368 -0.640058 -0.580938 -0.991529  
4   -0.585479 -0.365677 -0.833334 -0.887884 -0.826811 -0.819876 -0.996596  
..        ...       ...       ...       ...       ...       ...       ...  
267 -0.335076  1.089560 -0.049037 -0.385160 -0.342718 -0.081677 -0.855971  
268 -0.900055 -0.813437 -0.936275 -0.898733 -0.586853 -0.836350 -0.998654  
269 -0.936874 -0.738810 -0.926472 -0.945752 -0.744389 -0.826324 -0.998681  
270 -0.956864 -0.888063 -0.975490 -0.938516 -0.907145 -0.793863 -0.996860  
271 -0.860071 -0.716418 -0.887256 -0.905969 -0.745433 -0.871529 -0.998918  

[272 rows x 1281 columns]

In [7]:
y_test2 = df_test[0].values
y_test2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
X_test2 = df_test.drop([0],axis=1).values
X_test2

array([[-0.979046 , -0.716633 , -0.981584 , ..., -0.581632 , -0.841275 ,
        -0.99744  ],
       [-0.887534 , -0.0575993, -0.963168 , ..., -0.727701 , -0.545253 ,
        -0.966538 ],
       [-0.976713 , -0.802425 , -0.970534 , ..., -0.74961  , -0.756818 ,
        -0.993245 ],
       ...,
       [-0.98838  , -0.857016 , -0.922653 , ..., -0.744389 , -0.826324 ,
        -0.998681 ],
       [-0.972186 , -0.915509 , -0.89687  , ..., -0.907145 , -0.793863 ,
        -0.99686  ],
       [-0.950626 , -0.613945 , -0.841619 , ..., -0.745433 , -0.871529 ,
        -0.998918 ]])

In [35]:
X_test= scaler.transform(X_test2)

In [36]:

X_test_norm = fs.transform(X_test)

In [37]:
X_test_norm.shape

(272, 600)

In [ ]:
y_predict = grid.predict(X_test_norm)
print("Test accuracy : "+str(sum(y_test2 == y_predict)/len(y_test2)*100))